### ISSUE TITLE
Data missing

### ISSUE THREAD

**Issue by muellsen** [edfadeev/Bact-comm-PS85#1]
The files 

amplicons_seeds_taxonomy.txt
OTU_contingency_table.csv

are missing in Data/Bacteria. Is an upload possible?

**Comment by edfadeev** [comment]
Dear Christian,
Thanks for being interested in our dataset and apologize for the missing files, they are there now.

Please note that due to the size of the file `OTU_contingency_table.csv` was zipped.

Best,
Eddie

**Comment by muellsen** [comment]
Eddie, this is amazing! Thank you so much!!! Much appreciated! 

/christian
